[[redirects]]
from = "https://www.detest.tremendous.ml/*"
to = "/de/:splat"
status = 200
force = true
[[redirects]]
from = "https://www.entest.tremendous.ml/*"
to = "/en/:splat"
status = 200
force = true
[[redirects]]
from = "https://www.detest.tremendous.ml/*"
to = "/de/404.html"
status = 404
force = false
[[redirects]]
from = "https://www.entest.tremendous.ml/*"
to = "/en/404.html"
status = 404
force = false
